import * as THREE from '/vendor/three.module.js';

const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
class InputManager{
 constructor(){this.x=0;this.z=0;this.jump=false;this.dive=false;this.touch=matchMedia('(pointer:coarse)').matches||navigator.maxTouchPoints>0;this.keys={};addEventListener('keydown',e=>{this.keys[e.code]=true;if(e.code==='Space')this.jump=true;if(e.code.includes('Shift'))this.dive=true});addEventListener('keyup',e=>this.keys[e.code]=false);if(this.touch)this.setupTouch()}
 setupTouch(){const st=$('#stick'),nub=st.firstElementChild;let id=null;const move=e=>{const t=[...e.changedTouches].find(t=>t.identifier===id);if(!t)return;const r=st.getBoundingClientRect(),dx=t.clientX-(r.left+r.width/2),dy=t.clientY-(r.top+r.height/2),m=Math.min(44,Math.hypot(dx,dy)),a=Math.atan2(dy,dx);this.x=Math.cos(a)*m/44;this.z=Math.sin(a)*m/44;nub.style.transform=`translate(${this.x*35}px,${this.z*35}px)`};st.addEventListener('touchstart',e=>{id=e.changedTouches[0].identifier;move(e)},{passive:false});st.addEventListener('touchmove',move,{passive:false});st.addEventListener('touchend',()=>{id=null;this.x=this.z=0;nub.style.transform=''});$('#jump').addEventListener('touchstart',e=>{e.preventDefault();this.jump=true});$('#dive').addEventListener('touchstart',e=>{e.preventDefault();this.dive=true})}
 update(){if(!this.touch){this.x=(this.keys.KeyD||this.keys.ArrowRight?1:0)-(this.keys.KeyA||this.keys.ArrowLeft?1:0);this.z=(this.keys.KeyS||this.keys.ArrowDown?1:0)-(this.keys.KeyW||this.keys.ArrowUp?1:0)}} consume(k){const v=this[k];this[k]=false;return v}}
class Effects{constructor(scene){this.scene=scene;this.items=[]}burst(pos,color=0xffffff,n=10){for(let i=0;i<n;i++){const m=new THREE.Mesh(new THREE.SphereGeometry(.07,5,4),new THREE.MeshBasicMaterial({color}));m.position.copy(pos);m.userData.v=new THREE.Vector3((Math.random()-.5)*4,Math.random()*3,(Math.random()-.5)*4);m.userData.life=.65;this.scene.add(m);this.items.push(m)}}update(dt){this.items=this.items.filter(m=>{m.userData.life-=dt;m.position.addScaledVector(m.userData.v,dt);m.userData.v.y-=5*dt;m.scale.setScalar(m.userData.life);if(m.userData.life<=0){this.scene.remove(m);return false}return true})}}
class Obstacle{constructor(mesh,type,data={}){this.mesh=mesh;this.type=type;this.data=data;this.t=0}update(dt){this.t+=dt;if(this.type==='spin')this.mesh.rotation.y+=dt*this.data.speed;if(this.type==='move')this.mesh.position.x=this.data.x+Math.sin(this.t*this.data.speed)*this.data.range}}
class Checkpoint{constructor(z,pos){this.z=z;this.pos=pos}}
class Course{
 constructor(scene){this.scene=scene;this.obstacles=[];this.checkpoints=[new Checkpoint(8,new THREE.Vector3(0,1,3)),new Checkpoint(-16,new THREE.Vector3(0,2,-17)),new Checkpoint(-42,new THREE.Vector3(0,2,-43)),new Checkpoint(-69,new THREE.Vector3(0,3,-70))];this.build()}
 mat(c){return new THREE.MeshStandardMaterial({color:c,roughness:.32,metalness:.05})} box(x,y,z,w,h,d,c){const m=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),this.mat(c));m.position.set(x,y,z);m.receiveShadow=m.castShadow=true;this.scene.add(m);return m}
 build(){this.box(0,0,5,13,1,15,0x684be8);this.box(0,0,-11,11,1,13,0xff9f43);this.box(0,0,-28,4,1,18,0x51d6c3);this.box(0,1,-46,10,1,14,0xf35d91);this.box(0,1.5,-62,3.4,1,18,0x7759df);this.box(0,2,-76,12,1,11,0xffcf45);this.box(0,3,-87,10,1,12,0x51c9e8);const ramp=this.box(0,2,-82,7,.8,8,0xff795f);ramp.rotation.x=-.22;
  for(const z of [-7,-13]){const pivot=new THREE.Group();pivot.position.set(0,1.05,z);const bar=this.box(0,0,0,11,.35,.45,0xfee95b);bar.parent.remove(bar);pivot.add(bar);this.scene.add(pivot);this.obstacles.push(new Obstacle(pivot,'spin',{speed:z===-7?1.7:-1.4}))}
  for(let i=0;i<3;i++){const p=this.box(0,.6,-22-i*6,4,.55,3,0x57a6ff);this.obstacles.push(new Obstacle(p,'move',{x:0,range:3.6,speed:1+i*.2}))}
  for(const x of [-3,3]){const b=new THREE.Mesh(new THREE.CylinderGeometry(1,1,2,16),this.mat(0xf4438b));b.rotation.x=Math.PI/2;b.position.set(x,2,-47);this.scene.add(b);b.userData.bumper=true}
  const gate=this.box(0,5,-89,10,.5,.5,0xffffff);this.box(-5,3.5,-89,.5,4,.5,0xffffff);this.box(5,3.5,-89,.5,4,.5,0xffffff);for(let i=0;i<18;i++){const c=this.box((Math.random()-.5)*70,-1,(Math.random()-.5)*110,1+Math.random()*2,1+Math.random()*5,1+Math.random()*2,[0x9374ed,0x58d5df,0xff7eb3][i%3]);c.rotation.set(Math.random(),Math.random(),Math.random())}}
 update(dt){this.obstacles.forEach(o=>o.update(dt))}}
class Player{
 constructor(scene,color=0xff477e,name=''){this.velocity=new THREE.Vector3();this.checkpoint=0;this.finished=false;this.spawn=new THREE.Vector3(0,1,7);this.mesh=new THREE.Group();const mat=new THREE.MeshStandardMaterial({color,roughness:.3});const body=new THREE.Mesh(new THREE.CapsuleGeometry(.55,.8,8,12),mat),face=new THREE.Mesh(new THREE.SphereGeometry(.4,12,8),new THREE.MeshStandardMaterial({color:0xd9fbff}));face.scale.set(1,.65,.3);face.position.set(0,.42,-.5);this.mesh.add(body,face);if(name){const c=document.createElement('canvas');c.width=256;c.height=64;const x=c.getContext('2d');x.font='700 28px Fredoka, sans-serif';x.textAlign='center';x.fillStyle='#33206f';x.fillText(name,128,36);x.strokeStyle='white';x.lineWidth=7;x.strokeText(name,128,36);x.fillStyle='#33206f';x.fillText(name,128,36);const s=new THREE.Sprite(new THREE.SpriteMaterial({map:new THREE.CanvasTexture(c),depthTest:false}));s.position.y=1.65;s.scale.set(3,0.75,1);this.mesh.add(s)}this.mesh.position.copy(this.spawn);scene.add(this.mesh)}
 reset(effects){this.mesh.position.copy(this.spawn);this.velocity.set(0,0,0);effects.burst(this.mesh.position,0x66ddff,16)}
 update(dt,input,course,effects){input.update();const d=new THREE.Vector3(input.x,0,input.z);if(d.length()>1)d.normalize();const speed=7.5;this.velocity.x=THREE.MathUtils.damp(this.velocity.x,d.x*speed,12,dt);this.velocity.z=THREE.MathUtils.damp(this.velocity.z,d.z*speed,12,dt);const y=this.mesh.position.y, ground=this.ground(course);const grounded=y<=ground+.08;if(grounded){this.mesh.position.y=ground;this.velocity.y=Math.max(0,this.velocity.y);if(input.consume('jump')){this.velocity.y=8.3;effects.burst(this.mesh.position,0xffffff,7)}}if(input.consume('dive')){const dir=d.length()?d:new THREE.Vector3(0,0,-1);this.velocity.addScaledVector(dir,7);this.velocity.y=Math.max(this.velocity.y,2.2);effects.burst(this.mesh.position,0xffe45f,10)}this.velocity.y-=20*dt;this.mesh.position.addScaledVector(this.velocity,dt);if(d.length())this.mesh.rotation.y=Math.atan2(-d.x,-d.z);course.checkpoints.forEach((c,i)=>{if(this.mesh.position.z<c.z&&this.checkpoint<i+1){this.checkpoint=i+1;this.spawn.copy(c.pos);effects.burst(this.mesh.position,0x5effb0,18)}});if(this.mesh.position.y<-7)this.reset(effects);if(this.mesh.position.z<-90)this.finished=true}
 ground(course){const z=this.mesh.position.z,x=Math.abs(this.mesh.position.x);if(z> -2&&z<13&&x<6.5)return 1;if(z>-18&&z<-4&&x<5.5)return 1;if(z>-38&&z<-19&&x<5)return 1;if(z>-53&&z<-39&&x<5)return 2;if(z>-72&&z<-53&&x<1.7)return 2.5;if(z>-92&&z<-68&&x<6)return 3;return -20}}
class NetworkManager{
 constructor(ui){this.ui=ui;this.remotes=new Map();this.handlers={};this.connect()}
 connect(){const url=(window.WOBBLE_WS_URL||`${location.protocol==='https:'?'wss':'ws'}://${location.host}/ws`);this.queue=[];this.ui.status('Waking up multiplayer service…');this.ws=new WebSocket(url);this.ws.onopen=()=>{this.ui.status('Connected — create or join a room.');this.queue.splice(0).forEach(m=>this.ws.send(m))};this.ws.onerror=()=>this.ui.error('Could not reach multiplayer. You can still play Single Player.');this.ws.onclose=()=>this.ui.status('Connection lost — return home to retry.');this.ws.onmessage=e=>{const m=JSON.parse(e.data);if(m.type==='hello')this.id=m.id;if(m.type==='error')this.ui.error(m.message);this.handlers[m.type]?.(m)}}
 on(t,f){this.handlers[t]=f}send(type,data={}){const m=JSON.stringify({type,...data});if(this.ws?.readyState===1)this.ws.send(m);else if(this.ws?.readyState===0){this.queue.push(m);this.ui.status('Connecting… your request is queued.')}else this.ui.error('Multiplayer is offline. Choose Single Player or retry.')};state(p){this.send('state',{state:{x:p.mesh.position.x,y:p.mesh.position.y,z:p.mesh.position.z,ry:p.mesh.rotation.y,checkpoint:p.checkpoint}})}}
class UI{
 constructor(){this.mode='single';$$('.chip').forEach(b=>b.onclick=()=>{this.mode=b.dataset.mode;$$('.chip').forEach(x=>x.classList.toggle('active',x===b));$('#single').classList.toggle('hidden',this.mode!=='single');$('#multi').classList.toggle('hidden',this.mode!=='multi')});$$('.back').forEach(b=>b.onclick=()=>location.reload());$('#quality').onclick=()=>{document.body.dataset.low=document.body.dataset.low? '':'';$('#quality').textContent=document.body.dataset.low?'✨ QUALITY: LOW':'✨ QUALITY: HIGH'} }
 show(id){['menu','lobby','finish'].forEach(x=>$('#'+x).classList.add('hidden'));if(id)$('#'+id).classList.remove('hidden')}
 status(s){$('#connectStatus').textContent=s}error(s){const e=$('#error');e.textContent=s;e.classList.remove('hidden');setTimeout(()=>e.classList.add('hidden'),5000)}
 lobby(m,id){this.show('lobby');$('#roomCode').textContent=m.code;$('#players').innerHTML=m.players.map(p=>`<div class="player-row"><span>${p.id===m.host?'👑 ':''}${p.name}</span><b class="${p.ready?'ready':''}">${p.ready?'READY':'WAITING'}</b></div>`).join('');const host=m.host===id;$('#start').classList.toggle('hidden',!host);$('#start').disabled=!m.players.every(p=>p.ready)}
 hud(on,multi=false){$('#hud').classList.toggle('hidden',!on);$('#touch').classList.toggle('hidden',!on||!game.input.touch);$('#placeBox').classList.toggle('hidden',!multi)}
 finish(time,board){this.hud(false);this.show('finish');$('#finishTime').textContent=`TIME  ${this.time(time)}`;$('#board').innerHTML=board?.map((p,i)=>`<div class="board-row"><b>${i+1}</b><span>${p.name}</span><span>${this.time(p.time)}</span></div>`).join('')||'';$('#again').classList.toggle('hidden',!!board);$('#rematch').classList.toggle('hidden',!board)}time(ms){const m=Math.floor(ms/60000),s=Math.floor(ms/1000)%60,c=Math.floor(ms/10)%100;return `${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}.${String(c).padStart(2,'0')}`}}
class Game{
 constructor(){this.ui=new UI();this.input=new InputManager();this.canvas=$('#game');this.renderer=new THREE.WebGLRenderer({canvas:this.canvas,antialias:devicePixelRatio<2,alpha:true});this.renderer.setPixelRatio(Math.min(devicePixelRatio,1.75));this.renderer.shadowMap.enabled=!this.input.touch;this.scene=new THREE.Scene();this.scene.fog=new THREE.Fog(0x8ee4ef,45,120);this.camera=new THREE.PerspectiveCamera(58,1,.1,180);this.scene.add(new THREE.HemisphereLight(0xffffff,0x6f4bb7,2.2));const sun=new THREE.DirectionalLight(0xffffff,2.5);sun.position.set(10,20,10);sun.castShadow=true;this.scene.add(sun);this.course=new Course(this.scene);this.effects=new Effects(this.scene);this.mode='single';this.running=false;this.last=performance.now();this.bind();this.resize();addEventListener('resize',()=>this.resize());requestAnimationFrame(t=>this.loop(t))}
 bind(){$('#play').onclick=()=>this.start('single');$('#again').onclick=()=>this.start('single');$('#create').onclick=()=>{this.net??=this.setupNet();this.net.send('create',{name:$('#name').value})};$('#join').onclick=()=>{this.net??=this.setupNet();this.net.send('join',{name:$('#name').value,code:$('#code').value})};$('#ready').onclick=()=>{this.ready=!this.ready;this.net.send('ready',{ready:this.ready});$('#ready').textContent=this.ready?'NOT READY':'READY UP'};$('#start').onclick=()=>this.net.send('start');$('#rematch').onclick=()=>this.net.send('rematch')}
 setupNet(){const n=new NetworkManager(this.ui);n.on('lobby',m=>{this.room=m;this.ui.lobby(m,n.id)});n.on('start',m=>{const delay=Math.max(0,m.at-Date.now());setTimeout(()=>this.start('multi'),delay)});n.on('state',m=>{if(m.id===n.id||!this.player)return;let r=this.remotes.get(m.id);if(!r){r=new Player(this.scene,0x49dbe7,this.room?.players.find(p=>p.id===m.id)?.name||'Wobbler');this.remotes.set(m.id,r)}r.target=m.state});n.on('finish',m=>{if(m.id===n.id)this.ui.finish(this.elapsed,m.board)});return n}
 async start(mode){this.mode=mode;this.ui.show();this.player&&this.scene.remove(this.player.mesh);this.remotes?.forEach(r=>this.scene.remove(r.mesh));this.remotes=new Map();this.player=new Player(this.scene);this.player.checkpoint=0;this.running=true;this.started=performance.now();this.ui.hud(true,mode==='multi');$('#countdown').classList.remove('hidden');for(const x of ['3','2','1','GO!']){$('#countdown').textContent=x;await new Promise(r=>setTimeout(r,500))}$('#countdown').classList.add('hidden');this.started=performance.now()}
 resize(){this.camera.aspect=innerWidth/innerHeight;this.camera.updateProjectionMatrix();this.renderer.setSize(innerWidth,innerHeight,false)}
 loop(t){const dt=Math.min(.04,(t-this.last)/1000);this.last=t;this.course.update(dt);this.effects.update(dt);if(this.running&&this.player){this.player.update(dt,this.input,this.course,this.effects);this.elapsed=t-this.started;$('#timer').textContent=this.ui.time(this.elapsed);$('#checks').textContent=`${this.player.checkpoint} / 4`;const want=new THREE.Vector3(this.player.mesh.position.x*.3,this.player.mesh.position.y+5,this.player.mesh.position.z+9);this.camera.position.lerp(want,1-Math.exp(-5*dt));this.camera.lookAt(this.player.mesh.position.x,this.player.mesh.position.y+1,this.player.mesh.position.z-3);this.remotes.forEach(r=>{if(r.target){r.mesh.position.lerp(new THREE.Vector3(r.target.x,r.target.y,r.target.z),.18);r.mesh.rotation.y=r.target.ry}});if(this.mode==='multi'&&t%(1000/12)<20)this.net?.state(this.player);if(this.player.finished){this.running=false;this.effects.burst(this.player.mesh.position,0xffdf4e,30);if(this.mode==='single')this.ui.finish(this.elapsed);else this.net.send('finish')}}this.renderer.render(this.scene,this.camera);requestAnimationFrame(x=>this.loop(x))}}
let game;try{game=new Game()}catch(e){$('#error').textContent='3D graphics could not start: '+e.message;$('#error').classList.remove('hidden');console.error(e)}
