from pathlib import Path


def replace(path, old, new):
    p = Path(path)
    text = p.read_text()
    if old not in text:
        raise SystemExit(f"missing patch anchor in {path}: {old[:80]!r}")
    p.write_text(text.replace(old, new, 1))


install = "deploy/install.sh"
replace(
    install,
    'SAVED_SHARED_443_FALLBACK="127.0.0.1:14443"\n',
    'SAVED_SHARED_443_FALLBACK="127.0.0.1:14443"\nSAVED_RELEASE_TAG=""\n',
)
replace(
    install,
    'BRANCH="${BRANCH:-main}"\nDOMAIN="${DOMAIN:-$SAVED_DOMAIN}"\n',
    'BRANCH="${BRANCH:-main}"\n# An explicitly empty RELEASE_TAG switches back to branch deployment; otherwise the last\n# successful release remains pinned across ordinary no-argument updates.\nRELEASE_TAG="${RELEASE_TAG-${SAVED_RELEASE_TAG:-}}"\nDOMAIN="${DOMAIN:-$SAVED_DOMAIN}"\n',
)
replace(
    install,
    'if [ "$(id -u)" -ne 0 ]; then\n  fail "Запускать нужно от root: sudo bash deploy/install.sh"\nfi\n\n',
    'if [ "$(id -u)" -ne 0 ]; then\n  fail "Запускать нужно от root: sudo bash deploy/install.sh"\nfi\n\nif [ -n "$RELEASE_TAG" ] &&\n  ! [[ "$RELEASE_TAG" =~ ^v[0-9]+\\.[0-9]+\\.[0-9]+(-[0-9A-Za-z]+([.-][0-9A-Za-z]+)*)?$ ]]; then\n  fail "RELEASE_TAG должен выглядеть как v2.6.0 или v2.6.0-beta.1"\nfi\n\n',
)
old_checkout = '''if [ -d "$APP_DIR/.git" ]; then
  git -C "$APP_DIR" fetch --depth 1 origin "$BRANCH"
  git -C "$APP_DIR" reset --hard "origin/${BRANCH}"
else
  rm -rf "$APP_DIR"
  git clone --depth 1 --branch "$BRANCH" "$REPO" "$APP_DIR"
fi
chown -R "$APP_USER:$APP_USER" "$APP_DIR"
'''
new_checkout = '''if [ -n "$RELEASE_TAG" ]; then
  if [ ! -d "$APP_DIR/.git" ]; then
    rm -rf "$APP_DIR"
    git init -q "$APP_DIR"
    git -C "$APP_DIR" remote add origin "$REPO"
  fi
  say "Фиксированный release ${RELEASE_TAG}"
  git -C "$APP_DIR" fetch --force --depth 1 origin \
    "+refs/tags/${RELEASE_TAG}:refs/tags/${RELEASE_TAG}"
  release_commit="$(git -C "$APP_DIR" rev-parse "${RELEASE_TAG}^{commit}")"
  git -C "$APP_DIR" checkout --detach --force "$release_commit"
else
  if [ -d "$APP_DIR/.git" ]; then
    git -C "$APP_DIR" fetch --depth 1 origin "$BRANCH"
    git -C "$APP_DIR" reset --hard "origin/${BRANCH}"
  else
    rm -rf "$APP_DIR"
    git clone --depth 1 --branch "$BRANCH" "$REPO" "$APP_DIR"
  fi
fi
chown -R "$APP_USER:$APP_USER" "$APP_DIR"
'''
replace(install, old_checkout, new_checkout)
replace(
    install,
    'say "Зависимости"\ncd "$APP_DIR"\n',
    'if [ -n "$RELEASE_TAG" ]; then\n  say "Проверка release ${RELEASE_TAG}"\n  node "$APP_DIR/deploy/check-release.mjs" "$RELEASE_TAG" >/dev/null ||\n    fail "release ${RELEASE_TAG} не совпадает с выбранным commit/package version"\nfi\n\nsay "Зависимости"\ncd "$APP_DIR"\n',
)
replace(
    install,
    'build_sha="$(git -C "$APP_DIR" rev-parse HEAD)"\nif grep -q \'^WOBBLE_BUILD_SHA=\' /etc/wobble.env; then\n',
    'build_sha="$(git -C "$APP_DIR" rev-parse HEAD)"\nif grep -q \'^WOBBLE_RELEASE_TAG=\' /etc/wobble.env; then\n  sed -i "s/^WOBBLE_RELEASE_TAG=.*/WOBBLE_RELEASE_TAG=${RELEASE_TAG}/" /etc/wobble.env\nelse\n  printf \'\\n# Generated by deploy/install.sh for release identity.\\nWOBBLE_RELEASE_TAG=%s\\n\' "$RELEASE_TAG" >>/etc/wobble.env\nfi\nif grep -q \'^WOBBLE_BUILD_SHA=\' /etc/wobble.env; then\n',
)
replace(
    install,
    'say "Deploy smoke"\nif bash "$APP_DIR/deploy/smoke.sh" --require-backup; then\n',
    'say "Deploy smoke"\nexpected_version="$(node -p "require(\'./package.json\').version")"\nif SMOKE_EXPECT_VERSION="$expected_version" \\\n  SMOKE_EXPECT_COMMIT="${build_sha:0:12}" \\\n  SMOKE_EXPECT_RELEASE="$RELEASE_TAG" \\\n  bash "$APP_DIR/deploy/smoke.sh" --require-backup; then\n',
)
replace(
    install,
    "SAVED_SHARED_443_FALLBACK='${SHARED_443_FALLBACK}'\nCONF\n",
    "SAVED_SHARED_443_FALLBACK='${SHARED_443_FALLBACK}'\nSAVED_RELEASE_TAG='${RELEASE_TAG}'\nCONF\n",
)
replace(
    install,
    'echo\necho "Логи:        journalctl -u wobble -f"\n',
    'if [ -n "$RELEASE_TAG" ]; then\n  echo "Release:     ${RELEASE_TAG} @ ${build_sha:0:12}"\nfi\n\necho\necho "Логи:        journalctl -u wobble -f"\n',
)

smoke = "deploy/smoke.sh"
replace(
    smoke,
    'REQUIRE_BACKUP=0\n[ "${1:-}" = "--require-backup" ] && REQUIRE_BACKUP=1\n',
    'REQUIRE_BACKUP=0\n[ "${1:-}" = "--require-backup" ] && REQUIRE_BACKUP=1\nEXPECT_VERSION="${SMOKE_EXPECT_VERSION:-}"\nEXPECT_COMMIT="${SMOKE_EXPECT_COMMIT:-}"\nEXPECT_RELEASE="${SMOKE_EXPECT_RELEASE:-}"\n',
)
replace(
    smoke,
    '"$NODE_BIN" - "$health" "$REQUIRE_BACKUP" <<\'NODE\'\nconst health = JSON.parse(process.argv[2]);\nconst requireBackup = process.argv[3] === \'1\';\n',
    '"$NODE_BIN" - "$health" "$REQUIRE_BACKUP" "$EXPECT_VERSION" "$EXPECT_COMMIT" "$EXPECT_RELEASE" <<\'NODE\'\nconst health = JSON.parse(process.argv[2]);\nconst requireBackup = process.argv[3] === \'1\';\nconst expectedVersion = process.argv[4];\nconst expectedCommit = process.argv[5];\nconst expectedRelease = process.argv[6];\n',
)
replace(
    smoke,
    "if (health.ok !== true || health.service !== 'wobble-rush-3d') {\n  throw new Error('unexpected /health payload');\n}\n",
    "if (health.ok !== true || health.service !== 'wobble-rush-3d') {\n  throw new Error('unexpected /health payload');\n}\nif (expectedVersion && health.version !== expectedVersion) {\n  throw new Error(`unexpected version: ${health.version}, expected ${expectedVersion}`);\n}\nif (expectedCommit && health.commit !== expectedCommit) {\n  throw new Error(`unexpected commit: ${health.commit}, expected ${expectedCommit}`);\n}\nif (expectedRelease && health.release !== expectedRelease) {\n  throw new Error(`unexpected release: ${health.release}, expected ${expectedRelease}`);\n}\n",
)

build = Path("server/buildInfo.js")
text = build.read_text()
old = """function buildIdentity({ env = process.env, startedAt = PROCESS_STARTED_AT } = {}) {
  return {
    version: packageJson.version,
    commit: normalizeCommit(env.WOBBLE_BUILD_SHA || env.RENDER_GIT_COMMIT || env.GITHUB_SHA),
    startedAt
  };
}
"""
new = """function buildIdentity({ env = process.env, startedAt = PROCESS_STARTED_AT } = {}) {
  const identity = {
    version: packageJson.version,
    commit: normalizeCommit(env.WOBBLE_BUILD_SHA || env.RENDER_GIT_COMMIT || env.GITHUB_SHA),
    startedAt
  };
  const release = String(env.WOBBLE_RELEASE_TAG || '').trim();
  if (release) identity.release = release;
  return identity;
}
"""
if old not in text:
    raise SystemExit("missing build identity anchor")
build.write_text(text.replace(old, new, 1))

index = Path("server/index.js")
text = index.read_text()
anchor = "  commit: build.commit,\n  protocolVersion: PROTOCOL_VERSION,\n"
if anchor not in text:
    raise SystemExit("missing health build anchor")
index.write_text(
    text.replace(
        anchor,
        "  commit: build.commit,\n  release: build.release || null,\n  protocolVersion: PROTOCOL_VERSION,\n",
        1,
    )
)

pkg = Path("package.json")
text = pkg.read_text()
old = "server/releaseProcess.test.mjs server/observability.test.mjs"
if old not in text:
    raise SystemExit("missing package test anchor")
pkg.write_text(
    text.replace(
        old,
        "server/releaseProcess.test.mjs server/releaseDeploy.test.mjs server/observability.test.mjs",
        1,
    )
)

Path("server/releaseDeploy.test.mjs").write_text(
    r'''import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import test from 'node:test';
import buildInfo from './buildInfo.js';

const { buildIdentity } = buildInfo;
const install = readFileSync(new URL('../deploy/install.sh', import.meta.url), 'utf8');
const smoke = readFileSync(new URL('../deploy/smoke.sh', import.meta.url), 'utf8');

test('production installer can pin and persist an exact release tag', () => {
  assert.match(install, /RELEASE_TAG="\$\{RELEASE_TAG-\$\{SAVED_RELEASE_TAG:-\}\}"/);
  assert.match(install, /refs\/tags\/\$\{RELEASE_TAG\}:refs\/tags\/\$\{RELEASE_TAG\}/);
  assert.match(install, /checkout --detach --force "\$release_commit"/);
  assert.match(install, /check-release\.mjs" "\$RELEASE_TAG"/);
  assert.match(install, /SAVED_RELEASE_TAG='\$\{RELEASE_TAG\}'/);
});

test('deploy smoke can require the exact version, commit and release identity', () => {
  assert.match(smoke, /SMOKE_EXPECT_VERSION/);
  assert.match(smoke, /SMOKE_EXPECT_COMMIT/);
  assert.match(smoke, /SMOKE_EXPECT_RELEASE/);
  assert.match(smoke, /health\.release !== expectedRelease/);
});

test('build identity exposes a release tag only when production supplies one', () => {
  const plain = buildIdentity({ env: { WOBBLE_BUILD_SHA: 'abcdef0123456789' }, startedAt: 'now' });
  assert.equal(Object.hasOwn(plain, 'release'), false);
  const tagged = buildIdentity({
    env: { WOBBLE_BUILD_SHA: 'abcdef0123456789', WOBBLE_RELEASE_TAG: 'v2.6.0-beta.1' },
    startedAt: 'now'
  });
  assert.equal(tagged.release, 'v2.6.0-beta.1');
  assert.equal(tagged.commit, 'abcdef012345');
});
'''
)

docs = Path("docs/RELEASE-PROCESS.md")
docs.write_text(
    docs.read_text()
    + """

## Production deployment

After a release exists, deploy the exact tag instead of floating `main`:

```bash
RELEASE_TAG=v2.6.0-beta.1 bash /opt/wobble/deploy/install.sh
```

A successful tagged deployment stores `SAVED_RELEASE_TAG` in `/etc/wobble-deploy.conf`. Ordinary later runs stay pinned to that exact release. To deploy a newer release, pass its tag explicitly. To intentionally return to branch mode, pass an explicitly empty tag, for example `RELEASE_TAG= BRANCH=main bash /opt/wobble/deploy/install.sh`.

The installer verifies that the tag matches `package.json` and `package-lock.json`, checks out the tag commit detached, writes both release tag and build SHA into the service environment, and requires the deploy smoke to observe the expected version, commit and release identity from `/health`.
"""
)
