from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def replace_once(path, old, new):
    file = ROOT / path
    text = file.read_text(encoding='utf-8')
    count = text.count(old)
    if count != 1:
        raise SystemExit(f'{path}: expected one match, found {count}: {old[:100]!r}')
    file.write_text(text.replace(old, new, 1), encoding='utf-8')


# Keep unknown resource measurements unknown instead of turning null into numeric zero.
replace_once(
    'client/admin/admin.js',
    "function formatBytes(value) {\n  const bytes = Number(value);",
    "function formatBytes(value) {\n  if (value == null || value === '') return '—';\n  const bytes = Number(value);"
)
replace_once(
    'client/admin/admin.js',
    "function percent(value) {\n  const number = Number(value);",
    "function percent(value) {\n  if (value == null || value === '') return '—';\n  const number = Number(value);"
)
replace_once(
    'client/admin/admin.js',
    "      `свободно ${formatBytes(infra.resources?.disk?.availableBytes)}`,",
    "      diskUsed == null\n        ? 'измерение файловой системы недоступно'\n        : `свободно ${formatBytes(infra.resources?.disk?.availableBytes)}`,"
)

# Let the infrastructure loader return its health tone so refreshCurrent does not overwrite a red/warn
# snapshot with the generic green "data refreshed" message.
replace_once(
    'client/admin/admin.js',
    "  const tone = infrastructureTone(infra);\n  if (tone === 'good') setStatus('Серверные проверки не показывают явных проблем.', 'good');\n}\n\nasync function loadInfrastructure() {\n  const payload = await api('/api/admin/infrastructure', {});\n  renderInfrastructure(payload);\n}",
    "  return infrastructureTone(infra);\n}\n\nasync function loadInfrastructure() {\n  const payload = await api('/api/admin/infrastructure', {});\n  const tone = renderInfrastructure(payload);\n  if (tone === 'bad') {\n    return { statusText: 'Часть серверных проверок требует внимания. Посмотрите красные карточки ниже.', tone };\n  }\n  if (tone === 'warn') {\n    return { statusText: 'Сервер работает, но есть предупреждения, которые стоит проверить.', tone };\n  }\n  return { statusText: 'Серверные проверки не показывают явных проблем.', tone: 'good' };\n}"
)
replace_once(
    'client/admin/admin.js',
    "    await loader();\n    setStatus(`Данные обновлены в ${new Date().toLocaleTimeString('ru-RU')}`, 'good');",
    "    const result = await loader();\n    if (result?.statusText) setStatus(result.statusText, result.tone || '');\n    else setStatus(`Данные обновлены в ${new Date().toLocaleTimeString('ru-RU')}`, 'good');"
)

# Installer writes a single canonical HTTPS origin for SNI/certificate diagnostics. It is safe to
# overwrite because this variable is generated deployment metadata, not a user browser allowlist.
needle = '''fi

build_sha="$(git -C "$APP_DIR" rev-parse HEAD)"
'''
replacement = '''fi

# Канонический публичный HTTPS Origin нужен operational diagnostics. ALLOWED_ORIGINS может
# содержать несколько разрешённых browser origins, поэтому выбирать из него "первый" для SNI
# нельзя. Эта generated-настройка не секретная и всегда следует текущему deploy mode.
public_origin=""
case "$desired_origin" in
  https://*) public_origin="$desired_origin" ;;
esac
if grep -q '^WOBBLE_PUBLIC_ORIGIN=' /etc/wobble.env; then
  sed -i "s|^WOBBLE_PUBLIC_ORIGIN=.*|WOBBLE_PUBLIC_ORIGIN=${public_origin}|" /etc/wobble.env
else
  printf '\\n# Generated by deploy/install.sh for operational TLS/SNI checks.\\nWOBBLE_PUBLIC_ORIGIN=%s\\n' \
    "$public_origin" >>/etc/wobble.env
fi

build_sha="$(git -C "$APP_DIR" rev-parse HEAD)"
'''
replace_once('deploy/install.sh', needle, replacement)

# Explain why this variable is separate from the browser allowlist.
replace_once(
    'docs/INFRASTRUCTURE-STATUS.md',
    'Проверка HTTPS делает настоящий TLS handshake с `127.0.0.1:443`, но передаёт production SNI из\n`ALLOWED_ORIGINS`. Поэтому она проверяет именно маршрут Wobble через Nginx stream и реально выдаваемый\nсертификат, а не просто наличие файла сертификата на диске.',
    'Проверка HTTPS делает настоящий TLS handshake с `127.0.0.1:443`, но передаёт production SNI из\nканонического `WOBBLE_PUBLIC_ORIGIN`, который поддерживает installer. Это отдельная generated-настройка:\n`ALLOWED_ORIGINS` может содержать несколько разрешённых browser origins и поэтому не является надёжным\nисточником production hostname. В ручной/local установке допустим fallback только когда HTTPS origin в\n`ALLOWED_ORIGINS` ровно один. Поэтому проверяется именно маршрут Wobble через Nginx stream и реально\nвыдаваемый сертификат, а не просто наличие файла сертификата на диске.'
)

print('PR71 review fixes applied')
