import * as THREE from '/vendor/three.module.js';
import {COLORS,DIFFICULTIES,FIRST_SEGMENT_CENTER,SEGMENT_LENGTH,courseName,courseSpec,seededRandom} from '../core/Config.js';

const palette=[COLORS.purple,COLORS.orange,COLORS.cyan,COLORS.pink,COLORS.blue,COLORS.mint,COLORS.yellow];
const PLAYER_FOOT=.48;

export class Course{
  constructor(scene,spec,{quality='high'}={}){
    this.scene=scene;this.spec={...courseSpec(spec.seed,spec.difficulty),...spec};this.quality=quality;this.group=new THREE.Group();this.group.name='procedural-course';this.scene.add(this.group);this.platforms=[];this.obstacles=[];this.dynamic=[];this.scenery=[];this.cameraMeshes=[];this.rng=seededRandom(this.spec.seed);this.stageNames=[];this.build();
  }
  material(color,roughness=.3){return new THREE.MeshStandardMaterial({color,roughness,metalness:.03})}
  box({x=0,y=0,z=0,w=1,h=1,d=1,color=COLORS.purple,bevel=false,collider=true}={}){const geometry=bevel?new THREE.BoxGeometry(w,h,d,2,1,2):new THREE.BoxGeometry(w,h,d);const mesh=new THREE.Mesh(geometry,this.material(color));mesh.position.set(x,y,z);mesh.castShadow=this.quality!=='low';mesh.receiveShadow=true;this.group.add(mesh);if(collider){const platform={mesh,w,h,d,type:'box',lastPosition:mesh.position.clone(),delta:new THREE.Vector3()};this.platforms.push(platform);this.cameraMeshes.push(mesh);return platform}return{mesh,w,h,d,type:'decor'} }
  cylinder({x=0,y=0,z=0,r=1,h=.5,color=COLORS.pink,collider=false}={}){const mesh=new THREE.Mesh(new THREE.CylinderGeometry(r,r,h,this.quality==='low'?12:20),this.material(color));mesh.position.set(x,y,z);mesh.castShadow=this.quality!=='low';mesh.receiveShadow=true;this.group.add(mesh);if(collider){const platform={mesh,w:r*1.7,h,d:r*1.7,r,type:'cylinder',lastPosition:mesh.position.clone(),delta:new THREE.Vector3()};this.platforms.push(platform);return platform}return mesh}
  addRail(x,z,length,side=1){const rail=this.box({x,y:1.25,z,w:.16,h:1.1,d:length,color:0xffffff,collider:false}).mesh;rail.material.transparent=true;rail.material.opacity=.48;const posts=Math.ceil(length/4);for(let i=0;i<=posts;i++)this.box({x,y:.9,z:z-length/2+i*(length/posts),w:.22,h:1.3,d:.22,color:0xffffff,collider:false})}
  build(){
    this.addStart();const templates=this.pickTemplates();for(let i=0;i<this.spec.segmentCount;i++)this.addSegment(templates[i],i,FIRST_SEGMENT_CENTER-i*SEGMENT_LENGTH);this.addFinish();this.addCheckpointArches();this.addScenery();
  }
  pickTemplates(){const base=['sweepers','movers','bumpers','bridge','punchers','bounce','crosswind'];for(let i=base.length-1;i>0;i--){const j=Math.floor(this.rng()*(i+1));[base[i],base[j]]=[base[j],base[i]]}if(base[0]==='bridge')[base[0],base[2]]=[base[2],base[0]];while(base.length<this.spec.segmentCount)base.push(['sweepers','movers','bumpers','bounce'][Math.floor(this.rng()*4)]);return base.slice(0,this.spec.segmentCount)}
  addStart(){this.box({x:0,y:0,z:5,w:14,h:1,d:14,color:COLORS.purple,bevel:true});for(const x of [-6.4,6.4])this.addRail(x,5,12);const stripe=this.box({x:0,y:.515,z:-.8,w:13,h:.035,d:.85,color:COLORS.yellow,collider:false}).mesh;stripe.material.emissive=new THREE.Color(COLORS.yellow);stripe.material.emissiveIntensity=.18;for(let i=0;i<6;i++){const pad=this.cylinder({x:-4.5+i*1.8,y:.57,z:7.4,r:.62,h:.13,color:[COLORS.pink,COLORS.cyan,COLORS.yellow][i%3]});pad.scale.z=.68}}
  addSegment(type,index,z){const color=palette[(index+this.spec.seed)%palette.length],speed=DIFFICULTIES[this.spec.difficulty].speed;this.stageNames.push({sweepers:'SPIN PLAZA',movers:'SKY STEPS',bumpers:'BUMPER BOULEVARD',bridge:'TIGHTROPE TURN',punchers:'PUNCH PARADE',bounce:'BOUNCE GARDEN',crosswind:'WINDMILL WAY'}[type]);
    if(type==='sweepers'){
      this.box({x:0,y:0,z,w:12,h:1,d:18,color,bevel:true});this.addRail(-5.6,z,16);this.addRail(5.6,z,16);
      for(const [offset,direction] of [[4,1],[-4,-1]])this.addSpinner(0,.95,z+offset,10.4,.42,speed*(1.35+this.rng()*.45)*direction,index*.8+offset);
    }
    if(type==='movers'){
      this.box({x:0,y:0,z:z+7,w:11,h:1,d:4,color,bevel:true});this.box({x:0,y:0,z:z-7,w:11,h:1,d:4,color,bevel:true});
      for(let j=0;j<3;j++){const platform=this.box({x:0,y:.15+j*.12,z:z+3.5-j*3.5,w:3.8,h:.55,d:3,color:palette[(index+j+2)%palette.length],bevel:true});platform.motion={axis:'x',origin:0,range:3.8,speed:speed*(.82+j*.13),phase:j*2.15};this.dynamic.push(platform)}
    }
    if(type==='bumpers'){
      this.box({x:0,y:0,z,w:12,h:1,d:18,color,bevel:true});this.addRail(-5.6,z,16);this.addRail(5.6,z,16);
      const points=[[-3,5],[2.7,1],[-2.6,-3],[2.4,-6]];for(let j=0;j<points.length;j++)this.addBumper(points[j][0],1.25,z+points[j][1],.86,palette[(index+j+3)%palette.length]);
    }
    if(type==='bridge'){
      this.box({x:0,y:0,z,w:3.4,h:1,d:18,color,bevel:true});this.addRail(-1.55,z,16);this.addRail(1.55,z,16);this.addSpinner(0,1,z,7,.38,speed*1.08,index*.55);
      for(const side of [-1,1])for(let j=-1;j<=1;j++)this.box({x:side*3.4,y:-.25,z:z+j*5.2,w:2.3,h:.45,d:2.3,color:COLORS.cyan,collider:false}).mesh.rotation.y=j*.4;
    }
    if(type==='punchers'){
      this.box({x:0,y:0,z,w:11,h:1,d:18,color,bevel:true});this.addRail(-5.1,z,16);this.addRail(5.1,z,16);
      for(let j=0;j<3;j++){const p=this.box({x:j%2?3.7:-3.7,y:1,z:z+5-j*5,w:2.7,h:2.1,d:1.2,color:COLORS.pink,collider:false}).mesh;p.scale.z=.86;const obstacle={type:'puncher',mesh:p,originX:p.position.x,range:5.8,speed:speed*(1.4+j*.14),phase:j*2.2,w:2.7,d:1.2,radius:1.7};this.obstacles.push(obstacle)}
    }
    if(type==='bounce'){
      this.box({x:0,y:0,z,w:12,h:1,d:18,color,bevel:true});this.addRail(-5.6,z,16);this.addRail(5.6,z,16);for(const [x,oz] of [[-3,5],[2.5,2],[0,-2],[-2.7,-5.5]])this.addSpring(x,.68,z+oz,1.15);
    }
    if(type==='crosswind'){
      this.box({x:0,y:0,z,w:9,h:1,d:18,color,bevel:true});this.addRail(-4.1,z,16);this.addRail(4.1,z,16);for(const [j,oz] of [[0,4.8],[1,-.2],[2,-5]])this.addSpinner(j%2?2.2:-2.2,1.1,z+oz,7.2,.34,speed*(1.55+j*.14)*(j%2?-1:1),j);
    }
    const endZ=-18*(index+1);this.box({x:0,y:.53,z:endZ,w:type==='bridge'?3.25:Math.min(10,type==='movers'?10:11),h:.055,d:.48,color:COLORS.mint,collider:false}).mesh.material.emissive=new THREE.Color(COLORS.mint);
  }
  addSpinner(x,y,z,length,width,speed,phase){const pivot=new THREE.Group();pivot.position.set(x,y,z);const bar=new THREE.Mesh(new THREE.BoxGeometry(length,.38,width),this.material(COLORS.yellow,.24));bar.castShadow=true;pivot.add(bar);const hub=this.cylinder({x,y:y+.18,z,r:.5,h:.75,color:COLORS.purpleDark});this.group.add(pivot);this.obstacles.push({type:'spinner',mesh:pivot,length,width,speed,phase,center:new THREE.Vector3(x,y,z),height:.7})}
  addBumper(x,y,z,radius,color){const base=this.cylinder({x,y:.58,z,r:radius*1.12,h:.16,color:COLORS.yellow});const mesh=this.cylinder({x,y,z,r:radius,h:1.55,color});const ring=new THREE.Mesh(new THREE.TorusGeometry(radius*.82,.095,6,16),this.material(0xffffff,.2));ring.rotation.x=Math.PI/2;ring.position.set(x,y+.2,z);ring.castShadow=true;this.group.add(ring);this.obstacles.push({type:'bumper',mesh,radius,phase:this.rng()*6.28})}
  addSpring(x,y,z,radius){const pad=this.cylinder({x,y,z,r:radius,h:.25,color:COLORS.yellow});const inner=this.cylinder({x,y:y+.14,z,r:radius*.66,h:.05,color:COLORS.pink});this.obstacles.push({type:'spring',mesh:pad,radius,inner,phase:this.rng()*6.28})}
  addFinish(){const end=-18*this.spec.segmentCount;for(let j=0;j<4;j++)this.box({x:0,y:j*.32,z:end-2.4-j*2.2,w:8+j*.35,h:.65,d:2.45,color:palette[(this.spec.segmentCount+j)%palette.length],bevel:true});const finishCenter=this.spec.finishZ+1.5;this.box({x:0,y:1.02,z:finishCenter,w:11,h:.7,d:6,color:COLORS.yellow,bevel:true});for(const x of [-5,5])this.box({x,y:3.15,z:this.spec.finishZ,w:.42,h:4.3,d:.52,color:0xffffff,collider:false});this.box({x:0,y:5.05,z:this.spec.finishZ,w:10.4,h:.48,d:.55,color:0xffffff,collider:false});const ribbon=this.box({x:0,y:1.42,z:this.spec.finishZ,w:10,h:.08,d:.7,color:COLORS.pink,collider:false}).mesh;ribbon.material.emissive=new THREE.Color(COLORS.pink);ribbon.material.emissiveIntensity=.3;this.stageNames.push('VICTORY GATE')}
  addCheckpointArches(){for(let i=0;i<this.spec.checkpoints.length;i++){const z=this.spec.checkpoints[i],color=i===this.spec.checkpoints.length-1?COLORS.yellow:COLORS.mint;for(const x of [-5.1,5.1])this.box({x,y:1.9,z,w:.18,h:2.8,d:.18,color,collider:false});const top=this.box({x:0,y:3.25,z,w:10.4,h:.2,d:.2,color,collider:false}).mesh;top.material.emissive=new THREE.Color(color);top.material.emissiveIntensity=.25}}
  addScenery(){const count=this.quality==='low'?14:28;for(let i=0;i<count;i++){const side=i%2?-1:1,x=side*(10+this.rng()*34),z=10-this.rng()*(Math.abs(this.spec.finishZ)+45),y=-2+this.rng()*12;if(i%3===0){const cloud=new THREE.Group();for(let j=0;j<3;j++){const puff=new THREE.Mesh(new THREE.SphereGeometry(1.2+this.rng()*.9,8,6),new THREE.MeshLambertMaterial({color:0xffffff,transparent:true,opacity:.72}));puff.position.set(j*1.25,this.rng()*.6,this.rng()-.5);cloud.add(puff)}cloud.position.set(x,y+6,z);cloud.scale.setScalar(1+this.rng()*1.5);this.group.add(cloud);this.scenery.push({mesh:cloud,speed:(.15+this.rng()*.18)*side,baseX:x})}else{const piece=this.box({x,y,z,w:.8+this.rng()*2.5,h:1.5+this.rng()*5,d:.8+this.rng()*2.5,color:palette[i%palette.length],collider:false}).mesh;piece.rotation.set(this.rng(),this.rng(),this.rng());this.scenery.push({mesh:piece,speed:(this.rng()-.5)*.28,baseY:y})}}
  }
  update(dt,elapsed){for(const platform of this.dynamic){platform.lastPosition.copy(platform.mesh.position);const m=platform.motion,value=m.origin+Math.sin(elapsed*m.speed+m.phase)*m.range;platform.mesh.position[m.axis]=value;platform.delta.copy(platform.mesh.position).sub(platform.lastPosition)}for(const obstacle of this.obstacles){if(obstacle.type==='spinner'){obstacle.angle=elapsed*obstacle.speed+obstacle.phase;obstacle.mesh.rotation.y=obstacle.angle}else if(obstacle.type==='puncher'){obstacle.mesh.position.x=obstacle.originX+Math.sin(elapsed*obstacle.speed+obstacle.phase)*obstacle.range}else if(obstacle.type==='bumper'){obstacle.mesh.scale.y=1+Math.sin(elapsed*2.2+obstacle.phase)*.045}else if(obstacle.type==='spring'){const s=1+Math.sin(elapsed*3+obstacle.phase)*.04;obstacle.inner.scale.set(s,1,s)}}for(const item of this.scenery){if(item.baseX!==undefined)item.mesh.position.x=item.baseX+Math.sin(elapsed*.08+item.baseX)*2;item.mesh.rotation.y+=item.speed*dt}}
  surfaceAt(position,previousY,velocityY){let best=null;for(const p of this.platforms){const m=p.mesh,dx=Math.abs(position.x-m.position.x),dz=Math.abs(position.z-m.position.z);let inside=p.type==='cylinder'?Math.hypot(position.x-m.position.x,position.z-m.position.z)<p.r-.12:dx<p.w/2-.12&&dz<p.d/2-.12;if(!inside)continue;const top=m.position.y+p.h/2,foot=position.y-PLAYER_FOOT,previousFoot=previousY-PLAYER_FOOT;if(foot>top+.45||previousFoot<top-.48||velocityY>2.2)continue;if(!best||top>best.y)best={y:top,platform:p,delta:p.delta||new THREE.Vector3()}}return best}
  interact(player,now,effects){const pos=player.character.group.position,radius=.42;for(const o of this.obstacles){const key=o.mesh.uuid,last=player.hitTimes.get(key)||0;if(o.type==='spring'){const dx=pos.x-o.mesh.position.x,dz=pos.z-o.mesh.position.z;if(Math.hypot(dx,dz)<o.radius*.82&&Math.abs((pos.y-PLAYER_FOOT)-(o.mesh.position.y+.13))<.38&&player.velocity.y<=1&&now-last>.35){player.velocity.y=11.4;player.grounded=false;player.hitTimes.set(key,now);effects.burst(pos,COLORS.yellow,14,1.1);player.character.landed(.6)}continue}
      if(o.type==='bumper'){const dx=pos.x-o.mesh.position.x,dz=pos.z-o.mesh.position.z,dist=Math.hypot(dx,dz)||.01,min=o.radius+radius;if(dist<min&&Math.abs(pos.y-o.mesh.position.y)<1.55&&now-last>.28){const nx=dx/dist,nz=dz/dist;pos.x=o.mesh.position.x+nx*min;pos.z=o.mesh.position.z+nz*min;player.velocity.x=nx*10;player.velocity.z=nz*10;player.velocity.y=Math.max(6.2,player.velocity.y);player.grounded=false;player.hitTimes.set(key,now);effects.burst(pos,o.mesh.material.color.getHex(),16,1.15)}continue}
      if(o.type==='spinner'){const dx=pos.x-o.center.x,dz=pos.z-o.center.z,cos=Math.cos(o.angle),sin=Math.sin(o.angle),along=dx*cos-dz*sin,cross=dx*sin+dz*cos;if(Math.abs(along)<o.length/2+radius&&Math.abs(cross)<o.width/2+radius&&Math.abs(pos.y-o.center.y)<1.05&&now-last>.32){const side=Math.sign(cross)||1,nx=sin*side,nz=cos*side;pos.x+=nx*(o.width/2+radius-Math.abs(cross)+.04);pos.z+=nz*(o.width/2+radius-Math.abs(cross)+.04);const tangential=Math.min(12,Math.abs(o.speed)*Math.abs(along)*.72+5.5);player.velocity.x=nx*tangential+o.speed*dz*.22;player.velocity.z=nz*tangential-o.speed*dx*.22;player.velocity.y=Math.max(4.6,player.velocity.y);player.grounded=false;player.hitTimes.set(key,now);effects.burst(pos,COLORS.yellow,12,1)}continue}
      if(o.type==='puncher'){const dx=pos.x-o.mesh.position.x,dz=pos.z-o.mesh.position.z;if(Math.abs(dx)<o.w/2+radius&&Math.abs(dz)<o.d/2+radius&&Math.abs(pos.y-o.mesh.position.y)<1.5&&now-last>.34){const dir=Math.sign(dx)||Math.sign(Math.cos(now*o.speed+o.phase))||1;pos.x+=dir*(o.w/2+radius-Math.abs(dx)+.05);player.velocity.x=dir*10.5;player.velocity.z-=3;player.velocity.y=Math.max(4.2,player.velocity.y);player.grounded=false;player.hitTimes.set(key,now);effects.burst(pos,COLORS.pink,12,1)}}}}
  checkpointFor(position,current){let next=current;while(next<this.spec.checkpoints.length&&position.z<this.spec.checkpoints[next]&&position.y>-3&&Math.abs(position.x)<10)next++;return next}
  spawnFor(checkpoint){if(checkpoint<=0)return new THREE.Vector3(this.spec.start.x,this.spec.start.y,this.spec.start.z);const z=this.spec.checkpoints[Math.min(checkpoint-1,this.spec.checkpoints.length-1)]+3.1;return new THREE.Vector3(0,1.15,z)}
  progress(position,checkpoint){const total=Math.abs(this.spec.finishZ-this.spec.start.z),travelled=Math.max(0,this.spec.start.z-position.z);return Math.max(checkpoint/this.spec.segmentCount,Math.min(.995,travelled/total))}
  stageAt(checkpoint){return this.stageNames[Math.min(checkpoint,this.stageNames.length-1)]||courseName(this.spec.seed)}
  dispose(){this.scene.remove(this.group);this.group.traverse(o=>{o.geometry?.dispose?.();if(Array.isArray(o.material))o.material.forEach(m=>m.dispose?.());else o.material?.dispose?.()});this.platforms.length=this.obstacles.length=this.dynamic.length=this.scenery.length=0}
}
