export class NetworkManager{
  constructor(ui){this.ui=ui;this.handlers=new Map();this.queue=[];this.id=null;this.roomCode=null;this.latency=NaN;this.pingAt=0;this.lastPing=0;this.lastState=0;this.intentionalClose=false}
  connect(){if(this.ws&&this.ws.readyState<=1)return;this.intentionalClose=false;const url=window.WOBBLE_WS_URL||`${location.protocol==='https:'?'wss':'ws'}://${location.host}/ws`;this.ui.status('Waking the multiplayer service…');this.ws=new WebSocket(url);this.ws.addEventListener('open',()=>{this.ui.status('Connected — choose create or join.');for(const item of this.queue.splice(0))this.ws.send(item)});this.ws.addEventListener('message',event=>{let message;try{message=JSON.parse(event.data)}catch{return}if(message.type==='hello')this.id=message.id;if(message.type==='error')this.ui.error(message.message||'Multiplayer request failed.');if(message.type==='pong'&&message.at===this.pingAt)this.latency=(performance.now()-this.lastPing)/2;this.emit(message.type,message)});this.ws.addEventListener('error',()=>this.ui.error('Multiplayer is unavailable. Single Player is still ready.'));this.ws.addEventListener('close',()=>{if(!this.intentionalClose){this.ui.status('Connection lost — retry create/join or play solo.');this.emit('disconnect',{})}})}
  on(type,handler){if(!this.handlers.has(type))this.handlers.set(type,new Set());this.handlers.get(type).add(handler);return()=>this.handlers.get(type)?.delete(handler)}
  emit(type,message){for(const handler of this.handlers.get(type)||[])handler(message)}
  send(type,data={}){const payload=JSON.stringify({type,...data});if(this.ws?.readyState===WebSocket.OPEN)this.ws.send(payload);else{this.connect();if(this.queue.length<8)this.queue.push(payload);this.ui.status('Connecting… your request is queued.')}}
  sendState(state){const now=performance.now();if(now-this.lastState<66)return;this.lastState=now;this.send('state',{state})}
  tick(){const now=performance.now();if(this.ws?.readyState===WebSocket.OPEN&&now-this.lastPing>3000){this.lastPing=now;this.pingAt=Date.now();this.send('ping',{at:this.pingAt})}}
  close(){this.intentionalClose=true;this.queue.length=0;if(this.ws?.readyState===WebSocket.OPEN)this.ws.send(JSON.stringify({type:'leave'}));this.ws?.close();this.ws=null;this.roomCode=null}
}
